projectcalico/libnetwork-plugin

libnetwork/docker_plugin.py, node_filesystem/etc/service/calico-driver/run, tests/unit/docker_plugin_test.py
1) Capability handshake - https://github.com/docker/libnetwork/pull/516
2) Interfaces are no longer lists - https://github.com/docker/libnetwork/pull/508
Also, add some debug logs (which won't be logged by default) to show the response JSON, and downgrade the flask logging from debug to info (debug was too spammy)
=> Update to handle API changes and improve logging

.gitignore, tests/st/utils/utils.py
As per https://github.com/docker/docker/pull/17218 , the network inspect output has changed to return a list of dictionaries (allowing inspect to take multiple network names.
PR also includes minor updates to .gitignore.
=> Handle change to network inspect UX

README.md, libnetwork/driver_plugin.py, tests/unit/driver_plugin_test.py
Allow subnet to be specified which selects IPs only from that subnet.  The subnet must be an IPPool - so the subnet CIDR must exactly match that of a configured Calico IP Pool
=> Use subnet option on docker network create to slect which Calico IP Pool to use

libnetwork/driver_plugin.py
Fix how we initiate the flask app error handler. Our old method was incompatible with the recent release of Flask 0.11+
Relevant issue:
https://github.com/pallets/flask/issues/1837#issuecomment-223359287
=> [UT/ST Fix] Fix initiation of error handler in flask

driver/network_driver.go
Tom,
Just a suggested fix (I haven't tested it, although compiler looks happy enough). Just always create profile rather than check first then create.
It's one less round trip (hardly worth it perhaps), a minor simplification, but also avoids race conditions where two threads may attempt to create the profile at the same time - which you could actually just fix by checking for the ResourceAlreadyExists error on the create.
=> Avoid race conditions on profile creation

Makefile
Not sure when it changed but the '-o' flag on 'docker save' needs to come
before the image names
Signed-off-by: Doug Davis <dug@us.ibm.com>
=> Reorder 'docker save' options

driver/network_driver.go
Fix for https://github.com/projectcalico/libnetwork-plugin/issues/107
=> Closing dockerCli to fix 'Too many open files' issue

Makefile
allow override of local uid, to allow running on OSX with docker-machine, where local uid != host uid.
example usage: `LOCAL_USER_ID=1000 make test-containerized`
=> allow override of local uid

Makefile
..now that the final version of 1.13 has shipped we can stop using an RC
=> Makefile: Use docker v1.13 in the tests

driver/network_driver.go, glide.lock, glide.yaml, main.go
Allocate/FreeNetwork are used for swarm-mode support in remote
plugins, which calico doesn't support. Stubbed versions of both are
added.
- Update and remove pinning of github.com/docker/go-plugins-helpers
- Update github.com/docker/go-connections dependency, including
update of calls to ServeUnix in main.go:main(). ServeUnix removed
group name lookup support.
Fixes https://github.com/projectcalico/libnetwork-plugin/issues/138 issue.
=> Add stubbed Allocate/FreeNetwork api methods

README.md, driver/ipam_driver.go, driver/network_driver.go, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/custom_wep_labelling/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go, utils/netns/netns.go, utils/test/test_utils.go
Fixes [#72 Add (back) IPv6 support](https://github.com/projectcalico/libnetwork-plugin/issues/72).
**Usage**
1. Start the libnetwork-plugin
```
sudo dist/libnetwork-plugin
```
2. Add an IPv6 address to the host
```
sudo ip addr add fd80:24e2:f998:72d7::1/112 dev eth1
```
3. Start calico/node, without using the calico/node libnetwork-plugin, also pass in the host IPv6 address
```
sudo calicoctl node run --disable-docker-networking --ip6=fd80:24e2:f998:72d7::1
```
4. Create an IPv6 network
```
docker network create --ipv6 -d calico --ipam-driver calico-ipam my_net
```
5. Run containers on the IPv6 network
```
docker run --net my_net --name workload-A -tid busybox
docker run --net my_net --name workload-B -tid busybox
```
6. Check IPv6 network connectivity
```
docker exec workload-A ping -6 …
```
=> Add IPv6 support

Makefile
It looks like that container `calico-etcd-ssl` is not used any more.
=> No need to remove `calico-etcd-ssl` in Makefile

Makefile, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go
Tests failing because output from the `ip route` within the container now includes the `scope link` indication.
=> ip route output now includes scope link

glide.lock, glide.yaml, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/custom_wep_labelling/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go
Update glide.yaml/lock to use latest libcalico-go release (1.5.0)
=> Rev libcalico-go to 1.5.0

driver/ipam_driver.go, driver/network_driver.go, glide.lock, glide.yaml, main.go, utils/log/log.go, utils/netns/netns.go
Updating the logrus import to use the new updated user name (which is lowercased). This will prevent import errors with vendoring going forward.
Requires projectcalico/libcalico-go#484
```release-note
None required
```
=> Update the import for logrus to use the updated username

Makefile
Fix for issue #162.
Signed-off-by: David Wilder <wilder@us.ibm.com>
This patch avoids a Ci failure we have been seeing on Semaphore for some time.  See issue #162   
Here is the failure.
```
$ make test-containerized
<cut>
• Failure [3.068 seconds]
Libnetwork Tests
/go/src/github.com/projectcalico/libnetwork-plugin/tests/default_environment/libnetwork_test.go:345
docker run ipv6
/go/src/github.com/projectcalico/libnetwork-plugin/tests/default_environment/libnetwork_test.go:342
creates a container on a network  and checks all assertions [It]
/go/src/github.com/projectcalico/libnetwork-plugin/tests/default_environment/libnetwork_test.go:341
Expected
<string>: 2001:db8:7f30:3859:b73a:3e8b:9882:1bc0 dev cali0  metric 256 
fe80::/64 dev cali0  metric 256 
unreachable default dev lo  metric -1 …
```
=> Enable ipv6 in the dind test container.

Makefile, glide.lock, glide.yaml
Pin libcalico-go import to the hash associated with v1.7.2 branch. Pin go_build version to 0.9 for latest CVE fixes. Passes `test-containerized`.
=> Update for libcalico-go v1.7.2; rev go-build

Dockerfile, Makefile, glide.lock, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go
Ensure Alpine gets pulled when building image to pick up security fixes.
Pin alpine and go-build for repeatability.  go-build v0.8 uses Go 1.8.5, which is appropriate for 2.6.x.
=> Pin Alpine to 3.6 and go-build to v0.8.

driver/network_driver.go, utils/netns/netns.go
Ref. https://github.com/projectcalico/calicoctl/issues/488
I've introduced an environment variable `CALICO_LIBNETWORK_VETH_MTU` to set the MTU of the veth pairs created by the Calico libnetwork plugin. As discussed in the issue above, this allows `FELIX_IPINIPMTU` to be controlled separately from the veth MTU.
Worth noting is that this extends the signature of `netns.CreateVeth`, and I'm not sure if there are any other packages that use this function.
This was tested manually, could not get the tests on master to run. I'll need some help/pointers on how to add this to the test suite.
Will this ever make it into 2.6, or should I add this to the 3.0 docs?
=> Set veth MTU using CALICO_LIBNETWORK_VETH_MTU

Dockerfile, Dockerfile-ppc64le, Makefile, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/custom_wep_labelling/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go
Signed-off-by: David Wilder <wilder@us.ibm.com>
I had a couple of issues getting test-containerized running on ppc64le.  At this point there is no official docker:dind container for ppc64le so I had to build my own.  I expect this to be resolved in the near future.  Test-containerized needs a docker client to be available for the go-build container to use. It is obtained it from the docker:dind images docker.  This should provided the latest version.  However, this assumes that the go_build container has the required dependencies for docker or that docker is static. This may not always be the case for ppc64le. To resolve this I added bin/docker as a build target making test-containerized dependent on it.  On x86 nothing should change and the docker client will be obtained from the dind …
=> Adding support for ppc64le.

driver/ipam_driver.go, tests/default_environment/libnetwork_test.go
libnetwork-plugin v1.1.1 (as part of calico v2.6.3) introduced a bug
where IPAM broken if a docker network was created with --subnet.
The encountered error was:
> docker: Error response from daemon: IpamDriver.RequestAddress:
Unexpected number of assigned IP addresses. A single address should be
assigned. Got []
The IPAM client's AutoAssign() method ignores AutoAssignArgs.IPv{4,6}Pools
and therefore does not appear to allocate any addresses unless numIPv4/6
is non-zero.
Fixes https://github.com/projectcalico/calico/issues/1512
```release-note
IPAM driver should still allocated addresses to if a docker network was created with an explicit --subnet.
```
=> IPAM: allocate when docker network has subnet

Makefile
Standard `ci` and `cd` targets to replace the messy one-liner scripts in Semaphore. Per all of the other projects.
```release-note
None required
```
=> Add standard ci and cd targets

.gitignore, Makefile, driver/ipam_driver.go, driver/network_driver.go, glide.lock, glide.yaml, main.go, tests/custom_if_prefix/libnetwork_env_var_test.go, tests/custom_wep_labelling/libnetwork_env_var_test.go, tests/default_environment/libnetwork_test.go, utils/test/test_utils.go
This PR make this plugin support calico v3, so we can use latest calicoctl manage now.  In this PR I do those things:
* use latest libcalico to implement ipam and network driver.
* set docker network endpoint in ippool's meta, thus we can find it without query docker api ( this will cause problem when system restart and plugin run in docker, both of docker and plugin were waiting each other)
* use hostname as default namespace, it's better when you have huge containers.
* tested fully and manually.
* I disable some tests because useless now. I think tests can cover whole cases.
=> supoort calico v3

glide.lock
Changes included:
https://github.com/projectcalico/libcalico-go/compare/edcbcf64348004bfeb0dc3882cd2790743ec7728...d23c790d2c91462a3eb64f8586b24b922159fd30
=> release 2.6: Update libcalico-go
