- Makefile
- tests/st/libnetwork/test_mainline_multi_host.py
- tests/st/utils/docker_host.py
- tests/st/utils/workload.py
> Move to new UX

- tests/st/libnetwork/test_mainline_single_host.py
- tests/st/test_base.py
- tests/st/utils/workload.py
> Basic logging

- tests/st/libnetwork/test_mainline_multi_host.py
- tests/st/libnetwork/test_mainline_single_host.py
- tests/st/utils/docker_host.py
- tests/st/utils/network.py
- tests/st/utils/utils.py
> STs for new UX

- README.md
- libnetwork/driver_plugin.py
- tests/unit/driver_plugin_test.py
Tom - having difficulty testing this.  AFAIK, we should get the Discover notifications when adding a new node to the cluster... I don't seem to be getting that at the moment.  Not getting 404s either.
> Add discover URLs to plugin

- libnetwork/driver_plugin.py
- tests/unit/driver_plugin_test.py
> Fix bug when specifying IP

- CONTRIBUTING.md
> Add contributing doc to repo

- tests/st/libnetwork/test_mainline_multi_host.py
> Introduce retries to ping function that often fails STs.

- driver/ipam_driver.go
- driver/network_driver.go
Do it based on the Gateway - see comment in code for more details
> Change the change for Calico IPAM

- driver/ipam_driver.go
- driver/network_driver.go
- main.go
- tests/st/libnetwork/test_assign_specific_ip.py
- utils/log/log.go
> Debug logging option added

- driver/ipam_driver.go
- driver/network_driver.go
- main.go
- utils/log/log.go
> Logging fixes

- driver/ipam_driver.go
- libnetwork_test.go
> ipam driver: block --gateway

- driver/network_driver.go
- libnetwork_test.go
> Network driver - block --internal from being used

- driver/ipam_driver.go
- libnetwork_test.go
> Reject ipam options from being passed in

- Makefile
> Makefile: Use new build container

- .gitignore
- Makefile
...and as a bonus, use the same make target inside and outside a
container.
> Makefile: Use go-build container for tests

- Makefile
Keep a Go pkg cache outside the container than can be used inside the
container.
Also, pass "-i" to the "go build" command so the cache is populated
> Makefile: Speed up containerized builds

- driver/network_driver.go
- tests/default_environment/libnetwork_test.go
Fixes https://github.com/projectcalico/libnetwork-plugin/issues/97
> Support user provided MAC addresses

- .gitignore
- README.md
- driver/network_driver.go
- tests/custom_wep_labelling/libnetwork_env_var_test.go
- tests/custom_wep_labelling/libnetwork_suite_test.go
- tests/default_environment/libnetwork_test.go
Start a Goroutine from CreateEndpoint to update WorkloadEndpoint.
Implementation for issue https://github.com/projectcalico/libnetwork-plugin/issues/102
> Update WorkloadEndpoint with labels

- driver/network_driver.go
- tests/default_environment/libnetwork_test.go
Fixes https://github.com/projectcalico/libnetwork-plugin/issues/122
> Reject unknown options

- driver/network_driver.go
Fixes https://semaphoreci.com/calico/libnetwork-plugin/branches/master/builds/355
> When reporting errors sort flags for consistency.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- README.md
- driver/ipam_driver.go
- driver/network_driver.go
- glide.lock
- glide.yaml
- main.go
- tests/custom_if_prefix/libnetwork_env_var_test.go
- tests/custom_wep_labelling/libnetwork_env_var_test.go
- tests/default_environment/libnetwork_test.go
- utils/log/log.go
- utils/netns/netns.go
- utils/test/test_utils.go
Merge changes from master and then update the pins.
> Fixing pins

- driver/network_driver.go
- glide.lock
- glide.yaml
> Rev libcalico-go to v1.7.3

- .github/PULL_REQUEST_TEMPLATE.md
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
> add release note to pull request template

- Makefile
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
```release-note
None required
```
> Pin docker version

- Makefile
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
Use calico/dind instead of docker 
```release-note
None required
```
> Pin version of dind used in order to fix semaphore tests

- README.md
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
Fixes https://github.com/projectcalico/libnetwork-plugin/issues/185
```release-note
None required
```
> Update readme to be clear about project status
